[changelog]
header = """
{% if version %}
# Release Notes for Version {{ version }}
{% endif %}
"""
body = """
{% if version %}
**Release Date: {{ timestamp | date(format="%Y-%m-%d") }}**

### What's Changed
{% for group, grouped_commits in commits | group_by(attribute="group") %}
#### {{ group }}
{% for commit in grouped_commits %}
- {{ commit.id | truncate(length=7, end="") }} {{ commit.message | split(pat="\n") | first | trim | split(pat=": ") | last }}
{% endfor %}
{% endfor %}
{% if previous.version and remote.github.owner and remote.github.repo %}
#### Full Changelog: [{{ previous.version }}...{{ version }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }})
{% elif previous.version %}
#### Full Changelog: {{ previous.version }}...{{ version }}
{% endif %}
{% endif %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = [
  { pattern = "\\((.*)\\)", replace = "" },
]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Tests" },
  { message = "^chore", group = "Chores" },
  { message = "^ci", group = "CI" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = "v0.0.0"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = "v0.1.0"
